@extends('layoutABC.layout')
@section('contenido')
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title ">Producto</h4>
                <p class="card-category"> Tabla de Producto<a href="{{route('producto.create')}}" class="btn btn-danger pull-right">Agregar Nuevo</a></p>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead class=" text-primary">
                        <th>
                            <b>clave</b>
                        </th>
                        <th>
                            <b>sku</b>
                        </th>
                        <th>
                            <b>skuVnpk</b>
                        </th>
                        <th>
                            <b>provedor</b>
                        </th>
                        <th>
                            <b>categoria</b>
                        </th>
                        <th>
                            <b>descripcion</b>
                        </th>
                        <th>
                            <b>descripcionE</b>
                        </th>
                        <th>
                            <b>costo</b>
                        </th>
                        <th>
                            <b>iva_costo</b>
                        </th>
                        <th>
                            <b>ieps_costo</b>
                        </th>
                        <th>
                            <b>total_costo</b>
                        </th>
                        <th>
                            <b>precioMayoreo</b>
                        </th>
                        <th>
                            <b>ivaPrecioMayoreo</b>
                        </th><th>
                            <b>iepsPrecioMayoreo</b>
                        </th>
                        <th>
                            <b>totalPrecioMayoreo</b>
                        </th>
                        <th>
                            <b>precioMedioMayoreo</b>
                        </th>
                        <th>
                            <b>ivaPrecioMedioMayoreo</b>
                        </th>
                        <th>
                            <b>iepsPrecioMedioMayoreo</b>
                        </th>
                        <th>
                            <b>totalPrecioMedioMayoreo</b>
                        </th>
                        <th>
                            <b>precioRetail</b>
                        </th>
                        <th>
                            <b>ivaPrecioRetail</b>
                        </th>
                        <th>
                            <b>iepsPrecioRetail</b>
                        </th>
                        <th>
                            <b>totalPrecioRetail</b>
                        </th>
                        <th>
                            <b>existencia</b>
                        </th>
                        <th>
                            <b>unidadMedida</b>
                        </th>
                        <th>
                            <b>Editar</b>
                        </th>
                        <th>
                            <b>Eliminar</b>
                        </th>

                        </thead>
                        <tbody>
                        @foreach($productos as $producto)
                            <tr>
                                <td>
                                    {{$producto->clave}}
                                </td>
                                <td>
                                    {{$producto->sku}}
                                </td>
                                <td>
                                    {{$producto->skuVnpk}}
                                </td>
                                <td>
                                    @if(is_null(\App\Provedor::find($producto->provedor)))
                                        <p class="text-danger">Falta Valor</p>
                                    @else
                                        {{\App\Provedor::find($producto->provedor)->nombre}}
                                    @endif
                                </td>
                                <td>
                                    @if(is_null(\App\Categoria::find($producto->categoria)))
                                        <p class="text-danger">Falta Valor</p>
                                    @else
                                        {{\App\Categoria::find($producto->categoria)->nombre}}
                                    @endif
                                </td>
                                <td>
                                    {{$producto->descripcion}}
                                </td>

                                <td>
                                    {{$producto->descripcionE}}
                                </td>
                                <td>
                                    {{$producto->costo}}
                                </td>
                                <td>
                                    {{$producto->iva_costo}}
                                </td>
                                <td>
                                    {{$producto->ieps_costo}}
                                </td>
                                <td>
                                    {{$producto->total_costo}}
                                </td>
                                <td>
                                    {{$producto->precio_Mayoreo}}
                                </td>
                                <td>
                                    {{$producto->iva_Precio_Mayoreo}}
                                </td>
                                <td>
                                    {{$producto->ieps_Precio_Mayoreo}}
                                </td>
                                <td>
                                    {{$producto->total_Precio_Mayoreo}}
                                </td>
                                <td>
                                    {{$producto->precio_Medio_Mayoreo}}
                                </td>
                                <td>
                                    {{$producto->iva_Precio_Medio_Mayoreo}}
                                </td>
                                <td>
                                    {{$producto->ieps_Precio_Medio_Mayoreo}}
                                </td>
                                <td>
                                    {{$producto->total_Precio_Medio_Mayoreo}}
                                </td>
                                <td>
                                    {{$producto->precio_Retail}}
                                </td>
                                <td>
                                    {{$producto->iva_Precio_Retail}}
                                </td>
                                <td>
                                    {{$producto->ieps_Precio_Retail}}
                                </td>
                                <td>
                                    {{$producto->total_Precio_Retail}}
                                </td>
                                <td>
                                    {{$producto->existencia}}
                                </td>
                                <td>
                                    @if(is_null(\App\UnidadMedida::find($producto->unidad_Medida)))
                                        <p class="text-danger">Falta Valor</p>
                                    @else
                                        {{\App\UnidadMedida::find($producto->unidad_Medida)->nombre}}
                                    @endif
                                </td>
                                <td>
                                    <a href="{{route('producto.show', $producto->id)}}" class="btn btn-primary">Editar</a>
                                </td>
                                <td>
                                    <form action="{{route('producto.destroy', $producto->id)}}" method="post">
                                        {{csrf_field()}}
                                        <input type="hidden" name="_method" value="DELETE">
                                        <button class="btn btn-danger">Eliminar</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection()